module_spec: https://tfhub.dev/google/imagenet/inception_v3/feature_vector/1
finetune_layers_after: 152
top_layers_after: 188
learning_rate: 0.001
lambda_reg: 0.00001
tl_margin: 1.5
n_epochs: 400
top_training_steps: 100
images_dir: data/devices
splits_dir: data/splits
bottleneck_dir: data/bottleneck
project_dir: tmp/semihard
train_subdir: train
projector_subdir: projector
val_subdir: val
top_model_subdir: top_model
top_model_val_subdir: top_val
n_way: 50
train_top_only: True
min_test: 6
val_ratio: 0.1
test_ratio: 0.1
rebuild: False
seed: 42
k_sample: 10
embed_dim: 128